[package]
name = "localsearch_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
approx = "0.5.1"
indicatif = "0.17.3"
rand = "0.8.5"
rand_pcg = "0.3.1"
rayon = "1.6.1"
thiserror = "1.0.38"

[lib]
name = "localsearch_rs"
